version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --omit=dev && npm run debug"
    ports:
      - 5000:5000
      - 9222:9222
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    depends_on:
      - mongo
    links:
      - mongo
